name: Publish to GHCR

on:
  push:

  workflow_dispatch:
    inputs:
        Reason:
          description: 'Reason to use workflow_dispatch'     
          required: true
          default: 'Update to Newer Version'

env: 
  IMAGE_NAME: "python-gradient"

jobs:
  push-ghcr:
    name: Push Docker Image to GHCR
    # Ensure test job passes before pushing image.
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin 

      - name: Build Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Push Docker image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION